### ISSUE TITLE
I have a question in kernel's cunit scheduler.

### ISSUE THREAD

**Issue by HojinNamm** [SAITPublic/PNMLibrary#1]
While testing imdb_demo provided by the PNMLibrary, I think, I found an issue in kernel's cunit scheduler. So I report that.

When application releases the assigned cunit, 
If the assigned cunit id is 0, then the release is being completed without waking up any processes waiting in the wait queue.

Here's the code in lib/pnm/sched.c where it happens.
pnm_sched_release_cunit() returns cunit id passed as an arguement.
So, cunit id is 0, then pnm_sched_release_and_wakeup() doesn't called.

```
int pnm_sched_release_cunit(struct pnm_sched *sched, uint8_t cunit)
{
        int ret = cunit;
 
        PNM_DBG("Releasing cunit %hhu\n", cunit);
 
        if (cunit >= sched->nr_cunits) {
                PNM_ERR("Invalid cunit value: %hhu\n", cunit);
                return -1;
        }
 
        pnm_sched_lock(sched);
        {
                ASSERT_EXCLUSIVE_ACCESS_SCOPED(sched->states);
                sched->states[cunit].state = IDLE_STATE;
        }
        pnm_sched_unlock(sched);
 
        return ret;
}
EXPORT_SYMBOL(pnm_sched_release_cunit);
```

```
int pnm_sched_release_and_wakeup(struct pnm_sched *sched, uint8_t cunit)
{
        int ret = pnm_sched_release_cunit(sched, cunit);
 
        if (ret > 0)
                pnm_sched_wakeup_queue(sched);
 
        return ret;
}
EXPORT_SYMBOL(pnm_sched_release_and_wakeup);
```

If the total number of cunits is 3, which is the default number, then the problem is small.
However, if there is only one cunit, then the process waiting for cunit allocation will continue to wait in the waitqueue.

Wouldn't it be necessary to change the if condition in the pnm_sched_release_and_wakeup() function to "ret >=0"?

**Comment by chefmax7** [comment]
Confirmed with following reprocase:
```bash
$ sudo modprobe imdb_resource nr_cunits=1
$ sudo build/tools/pnm_ctl setup-shm --imdb
$ ./build/test/imdb_demo imdb_data/
Start 1 job(s), output type - bit vectors...
#1 worker's device time (ms): 0
Real time (ms): 6579
Bandwidth (MEPS): 379.997
Throughput (QPS): 759.994

Start 5 job(s), output type - bit vectors...
... (hang)
```
@HojinNamm thank for reporting this bug. As a quick fix you can use the proposed change `ret >= 0`.
For the upstream fix, we are going to remove this code in next code update (I hope we can do it in near future @YongminTai).

**Comment by HojinNamm** [comment]
Okay. Thanks for answer :)
